### ISSUE TITLE
Split library and docs into 2 different repos?

### ISSUE THREAD

**Issue by datlechin** [spekulatius/PHPScraper#105]
Should we split the library and docs into 2 different repos?
Because when installing the library, we only use the `phpscraper.php` file, and the `website` directory is not necessary.

![Screenshot 2022-09-17 at 15 52 41](https://user-images.githubusercontent.com/56961917/190848860-ecfbdbaa-b8c9-44ae-8522-88bf837d343b.png)

**Comment by spekulatius** [comment]
Yeah, it's something I've been considering too. I didn't have this issue. It seems like it's a character problem.

I'll make a split off this over the next days. Feel free to continue with the translations and I'll ping you here so we can copy it over, okay?

**Comment by spekulatius** [comment]
Hey @datlechin,

I've removed the test pages and migrated them into a separate repo. See #106 

Can you rebase from origin/master to see if this problem is resolved? I'll migrate the website into a separate repo once the translations are completed :muscle: 

I hope this works for you :)

Cheers,
Peter
